#ifndef _DEFINES_H
#define _DEFINES_H

#define OUR_HEADERLEN 17

#define PROTO_VER 0x07

#define PACK_CODE_IN_HANDSHAKE 0x00
#define PACK_CODE_IN_BLOCK 0x05
#define PACK_CODE_IN_MOVEMENT 0x08
#define PACK_CODE_IN_CHAT 0x0D

#define PACK_CODE_OUT_SRVIDENTIFY 0x00
#define PACK_CODE_OUT_MAPINIT 0x02
#define PACK_CODE_OUT_MAPCHUNK 0x03
#define PACK_CODE_OUT_MAPFINISH 0x04
#define PACK_CODE_OUT_BLOCK 0x06
#define PACK_CODE_OUT_SPAWN 0x07
#define PACK_CODE_OUT_TELEPORT 0x08
#define PACK_CODE_OUT_MOVEANDHEAD 0x09
#define PACK_CODE_OUT_MOVE 0x0A
#define PACK_CODE_OUT_HEADING 0x0B
#define PACK_CODE_OUT_DESPAWN 0x0C
#define PACK_CODE_OUT_DISCONNECT 0x0E

#define PACKLEN_IN_HANDSHAKE 131
#define PACKLEN_IN_BLOCK 9
#define PACKLEN_IN_MOVEMENT 10
#define PACKLEN_IN_CHAT 66

#define PACKLEN_OUT_SRVIDENTIFY 131
#define PACKLEN_OUT_MAPSTART 1
#define PACKLEN_OUT_MAPCHUNK 1028
#define PACKLEN_OUT_MAPFINISH 7
#define PACKLEN_OUT_SPAWN 74
#define PACKLEN_OUT_CHAT 66
#define PACKLEN_OUT_DESPAWN 2
#define PACKLEN_OUT_DISCONNECT 65
#define PACKLEN_OUT_SENDBLOCK 8
#define PACKLEN_OUT_MOVEANDHEAD 10
#define PACKLEN_OUT_MOVE 5
#define PACKLEN_OUT_HEADING 4

#define PACKET_BROKE_STREAM 0xFE
#define PACKET_ERROR 0xFF

#define PACK_STRLEN 64
#define PACK_SHORTLEN 2
		//unsigned char 0xFF == -1

#endif